apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../app

patchesStrategicMerge:
- example-deploy-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: proxy-config
  files:
  - envoy.yaml

secretGenerator:
- name: opa-policy
  files:
  - policy.rego


