apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../app-w-policy

namespace: opa-envoy-tut-preprod

patchesJson6902:
- target:
    group: networking.k8s.io
    kind: Ingress
    name: example-app
    version: v1beta1
  path: example-ingress-patch.yaml